### PR TITLE
Changed miss named variables that caused checks to fail

### PR DESCRIPTION
**Pull request by Jessonsotoventura**
Fixes issue #21 
Looks like the variable name and the argument did not match, causing checks to fail

### CODE REVIEW

**Review by memo330179 — APPROVED** [review]
The application is no longer crashing.

**Comment by memo330179** [comment]
@agarwali needs to approve then it can be merged.

**Comment by Jessonsotoventura** [comment]
Oh so on the approval everyone listed needs to merge?

**Comment by memo330179** [comment]
No, I just thought it would be nice to get the person reporting the bug to approve as well. Might not work in practice though. We should just merge to keep codebase moving.

**Pull request merged**
