### PR TITLE
 "Template for all galleries view"

### PR DESCRIPTION
**Pull request by Chauwaj**
I finished working on the front end (initial work) and what I think it will look like based on the plan. Links to edit page,call for submissions and to create page are fully functional. I hard coded some of the table data such as deadline and number of submissions just for this sprint, I will in the next sprint work on pulling this data from the database and making the table expand dynamically depending on the number of galleries and information available.

### CODE REVIEW

**Comment by memo330179** [comment]
Changes are already in the master branch. We should create a pull request next time. The code looks good though!

**Comment by memo330179** [comment]
Styles should be in css file which needs to be named properly `app/static/css/local/<file>`

**Comment by Chauwaj** [comment]
Hey!

I must have made a mistake whem commiting my changes! My plan was to make a pull request like always. My issue has been closed though how can I fix this?

Thanks!




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by memo330179** [comment]
@Chauwaj It's fine. Since the code was already merged into master and it didn't break anything we figured that was good enough.

**Pull request closed without merging**
